spring:
    application:
        name: media-library
    datasource:
        url: jdbc:postgresql://{host}:{port}/{database name}
        username:
        password:
    jpa:
        hibernate:
            ddl-auto:

media-library:
    upload_dir: uploads